apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  labels:
    app: node-backend
    env: dev
    tier: backend 
  namespace: node-backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      name: node-backend
      labels:
        app: node-backend
    spec:
      containers:
      - name: node-backend
        image: gudditi/node-backend:10400445354
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: node-backend
        resources:
            limits:
                cpu: "500m"
                memory: "500Mi"
            requests:
                cpu: "200m"
                memory: "200Mi"