apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: node-backend
spec:
  hard:
    requests.cpu: "1000m"       # Total CPU requests limit
    requests.memory: "2Gi"      # Total memory requests limit
    limits.cpu: "2000m"         # Total CPU limits
    limits.memory: "4Gi"        # Total memory limits
    pods: "10"                  # Total number of pods
    services: "5"               # Total number of services
    persistentvolumeclaims: "5" # Total number of PVCs