apiVersion: v1
kind: Service
metadata:
  name: node-backend
  namespace: node-backend
spec:
  type: NodePort
  selector:
    app: node-backend

  ports:
  - name: node-backend-network
    protocol: TCP
    port: 3000
    targetPort: 3000