name: docker-ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSCODE }}

      - name: Docker Build-Push
        run: |
          docker build -t gudditi/node-backend:${{ github.run_id }} -f Node-backend/Dockerfile .
          docker build -t gudditi/node-frontend:${{ github.run_id }} -f Node-frontend/Dockerfile .
          docker push gudditi/node-frontend:${{ github.run_id }}
          docker push gudditi/node-backend:${{ github.run_id }}



      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     # context: Node-backend/
      #     file: Node-backend/Dockerfile
      #     push: true
      #     tags: gudditi/node-backend:${{ github.run_id }}


